### ISSUE TITLE
Shelly 2.5 - Blinds no longer work in Domoticz 2022.2

### ISSUE THREAD

**Issue by Sjonnie2018** [mario-peters/ShellyCloudPlugin#23]
**Sorry to "cross post" here on github but not having my blinds working is a bit of a pain ;-)

Hi all,

Updated to latest Domoticz stable yesterday and as of that moment all my Shelly 2.5 (Roller function) refuses to work. I have 10 Shelly's controlling my rollers. All refuse of course :-)

I checked to plugin.py to see if the plugin sends a open/close instead of on/off to the device and it does. So it seems the plugin should be working.

Anyone had this issue and found a solution?

TIA

EDIT 1: Could it be that the plugin is now using the "wrong" switchtype? In the plugin I see switchtype 13 (in createRoller(hostname, count)). I tried searching for the correct type (if there has been a change) but cannot find it.

EDIT 2: Found more info on the switchtype here: [https://www.domoticz.com/wiki/Developin ... hon_plugin](https://www.domoticz.com/wiki/Developing_a_Python_plugin). Don't know how to change the plugin though :(

**Comment by GeyerA** [comment]
Hi,
I can confirm that the roller function does not work anymore on 2022.2. I noticed since my Shelly 1 also started to show log-errors; errors which I did not have on 2022.1.
`2022-11-21 18:04:09.230 Error: Garage: Call to function 'onHeartbeat' failed, exception details:
2022-11-21 18:04:09.236 Error: Garage: Traceback (most recent call last):
2022-11-21 18:04:09.236 Error: Garage: File "/home/domoticz/plugins/ShellyCloudPlugin/plugin.py", line 364, in onHeartbeat
2022-11-21 18:04:09.236 Error: Garage: _plugin.onHeartbeat()
2022-11-21 18:04:09.236 Error: Garage: File "/home/domoticz/plugins/ShellyCloudPlugin/plugin.py", line 303, in onHeartbeat
2022-11-21 18:04:09.236 Error: Garage: updateSHSW1(json_request, self)
2022-11-21 18:04:09.237 Error: Garage: File "/home/domoticz/plugins/ShellyCloudPlugin/plugin.py", line 834, in updateSHSW1
2022-11-21 18:04:09.237 Error: Garage: updateMeter(meters[count], count, self)
2022-11-21 18:04:09.237 Error: Garage: File "/home/domoticz/plugins/ShellyCloudPlugin/plugin.py", line 966, in updateMeter
2022-11-21 18:04:09.237 Error: Garage: Devices[11+count].Update(nValue=0,sValue=power)
2022-11-21 18:04:09.237 Error: Garage: KeyError: 11`
As I now tried to close some rollers, command sent but no action. Here the message from log
`2022-11-21 18:09:05.693 Living Room: onCommand called for Unit 2: Parameter 'Close', Level: 0
2022-11-21 18:09:05.694 Living Room: Unknown command: Close
2022-11-21 18:09:05.694 Living Room: url: http://192.168.178.42
2022-11-21 18:09:05.671 Status: User: Admin (IP: 192.168.178.39) initiated a switch command (56/Living Room - 25-8CAAB55DB5F3/Close)`

UPDATE,
I restored 2022.1 version and still, roller did not work.

UPDATE2, maybe this commit helps.
[https://github.com/enesbcs/Shelly_MQTT/commit/311551643e915e8e5817d108ce8095e5a6d3aee0](url)

**Comment by GeyerA** [comment]
Hi, found the issue.
Since the log error was "Unknow command: Close" I just changed On to Open and Off to Close
`            if str(Command) == "On":
                if self.mode == "roller":
                    url = url + "?go=open"
                else:
                    url = url + "?turn=on"
            elif str(Command) == "Off":
                if self.mode == "roller":
                    url = url + "?go=close"
to`
`            if str(Command) == "Open":
                if self.mode == "roller":
                    url = url + "?go=open"
                else:
                    url = url + "?turn=on"
            elif str(Command) == "Close":
                if self.mode == "roller":
                    url = url + "?go=close"`
and all returned working. I will also mention in the tree...
Log however still looks like this
`2022-11-27 20:58:35.015 LivingRoomCloud: onCommand called for Unit 2: Parameter 'Open', Level: 100
2022-11-27 20:58:35.015 LivingRoomCloud: url: http://192.168.178.42/roller/0?go=open
2022-11-27 20:58:35.314 LivingRoomCloud: Unknown command: Open
2022-11-27 20:58:46.085 LivingRoomCloud: onHeartbeat called
2022-11-27 20:59:16.094 LivingRoomCloud: onHeartbeat called
2022-11-27 20:59:46.094 LivingRoomCloud: onHeartbeat called
2022-11-27 21:00:16.058 LivingRoomCloud: onHeartbeat called
2022-11-27 21:00:46.062 LivingRoomCloud: onHeartbeat called
2022-11-27 21:01:16.075 LivingRoomCloud: onHeartbeat called
2022-11-27 21:01:46.065 LivingRoomCloud: onHeartbeat called
2022-11-27 21:02:12.666 LivingRoomCloud: onCommand called for Unit 2: Parameter 'Close', Level: 0
2022-11-27 21:02:12.667 LivingRoomCloud: url: http://192.168.178.42/roller/0?go=close
2022-11-27 21:02:12.762 LivingRoomCloud: Unknown command: Close
2022-11-27 21:02:12.626 Status: User: Admin (IP: ::1) initiated a switch command (3/LivingRoomCloud - shellyswitch25-8CAAB55DB5F3_Roller1/Close)`

**Comment by DjTuxeedo** [comment]
Did someone actually solve this? At a first glance I suspect an API change from the Shelly side.
With my humble understanding of things I noticed that the URL for opening a Shelly 2.5 in roller mode has changed from:
<IPAdress>/roller/?go=open
to:
<IPAdress>/roller/<Index>/?go=open

Of course the index is always 0, as there is only one Roller connected to a single Shelly device. maybe they changed it to comply with that new Shelly Pro pm Which has 4 Channels and can control 2 Rollers. So they introduced an index in the URL (just guessing here).

Anyway this also explains why the "onheartbeat" function causes problems because the shelly device also answered with an indexed status message. I can't really fix the issue, i just hope it helps someone. 

Here is a Reference that might be helpful:
https://shelly-api-docs.shelly.cloud/gen1/#shelly2-5-settings-roller-index

**Comment by DjTuxeedo** [comment]
I can confirm, this Works. Thanks a lot. this makes things so much easier :-)
